# Generated by Django 3.1 on 2021-11-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StockManager', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StockManager.warehouse', verbose_name='Entrepot'),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.range'),
        ),
        migrations.AddField(
            model_name='labelling',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.range'),
        ),
        migrations.AddField(
            model_name='handle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handle_brand', to='Product.brand', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='handle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handle_color', to='Product.color', verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='combinedrange',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.color', verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='combinedrange',
            name='range_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.range'),
        ),
    ]
