# Generated by Django 3.1 on 2021-11-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contact', '0001_initial'),
        ('Machine', '0002_auto_20211103_2155'),
        ('Product', '0002_auto_20211103_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilType',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Capacité (L)')),
                ('link', models.CharField(blank=True, choices=[('AVEC_LIEN', 'Avec lien'), ('SANS_LIEN', 'Sans lien'), (None, '--------')], max_length=250, null=True, verbose_name='Lien de fermeture')),
                ('micronnage_ideal', models.FloatField(blank=True, default=0, null=True, verbose_name='Micronnage')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'capacity'],
            },
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='RawMatter',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('supplier', models.ManyToManyField(blank=True, to='Contact.Contact', verbose_name='Fournisseur')),
            ],
            options={
                'ordering': ['name', 'type_name', '-brand'],
            },
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='FinishedProductType',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Capacité (L)')),
                ('link', models.CharField(blank=True, choices=[('AVEC_LIEN', 'Avec lien'), ('SANS_LIEN', 'Sans lien'), (None, '--------')], max_length=250, null=True, verbose_name='Lien de fermeture')),
                ('micronnage', models.FloatField(blank=True, default=0, null=True, verbose_name='Micronnage')),
                ('bag_roll', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de sacs par rouleau')),
                ('roll_package', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de rouleaux par carton')),
                ('labelling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.labelling')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.package')),
            ],
            options={
                'ordering': ['name', 'capacity'],
            },
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Capacité (L)')),
                ('link', models.CharField(blank=True, choices=[('AVEC_LIEN', 'Avec lien'), ('SANS_LIEN', 'Sans lien'), (None, '--------')], max_length=250, null=True, verbose_name='Lien de fermeture')),
                ('micronnage', models.FloatField(blank=True, default=0, null=True, verbose_name='Micronnage')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('supplier', models.ManyToManyField(blank=True, to='Contact.Contact', verbose_name='Fournisseur')),
            ],
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Capacité (L)')),
                ('link', models.CharField(blank=True, choices=[('AVEC_LIEN', 'Avec lien'), ('SANS_LIEN', 'Sans lien'), (None, '--------')], max_length=250, null=True, verbose_name='Lien de fermeture')),
                ('micronnage', models.FloatField(blank=True, default=0, null=True, verbose_name='Micronnage')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('printing_date', models.DateTimeField(blank=True, null=True)),
                ('shaping_date', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING_EXTRUSION', "En cours d'extrustion"), ('PENDING_DATA', "En attente d'informations"), ('IN_STOCK', 'En Stock'), ('PENDING_PRINTING', "En cours d'impression"), ('PENDING_SHAPING', 'En cours de soudure'), ('CONSUMED', 'Consommée'), ('SOLD', 'Vendue'), ('QUARANTINE', 'En Quarantaine'), ('TO_BE_DESTROYED', 'A Détruire'), ('CUT', 'Coupée')], default='PENDING_EXTRUSION', max_length=25, null=True)),
                ('ext_validated', models.BooleanField(blank=True, default=False, null=True)),
                ('motive', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explication')),
                ('defective', models.CharField(blank=True, choices=[('DEFECTIVE', 'Défectueuse'), ('NON_DEFECTIVE', 'Normale')], default='NON_DEFECTIVE', max_length=250, null=True, verbose_name='Bobine Défectueuse')),
                ('printed', models.CharField(blank=True, choices=[('PRINTED', 'Imprimée'), ('NOT_PRINTED', 'Non Imprimée')], max_length=250, null=True, verbose_name='Impression')),
                ('cw1', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('cw2', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('cw3', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('cwm', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('is_sub', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dérivée')),
                ('destroyed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Détruite')),
                ('quarantine_level', models.IntegerField(blank=True, default=0, null=True)),
                ('ticket_printed', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coil_purchaser', to='Contact.contact', verbose_name='Client')),
                ('extrusion_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrudeuse', to='Machine.machine')),
                ('introducer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introducer', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.coil')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer', to=settings.AUTH_USER_MODEL)),
                ('printing_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imprimeuse', to='Machine.machine')),
                ('shaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaper', to=settings.AUTH_USER_MODEL)),
                ('shaping_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soudeuse', to='Machine.machine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coil_supplier', to='Contact.contact', verbose_name='Fournisseur')),
                ('type_coil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.coiltype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-status', '-creation_date'],
            },
            bases=('Product.product',),
        ),
    ]
