# Generated by Django 3.1 on 2021-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_coil_coiltype_finishedproduct_finishedproducttype_rawmatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='coiltype',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='combinedrange',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='finishedproducttype',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='labelling',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='package',
            name='capacity',
            field=models.CharField(blank=True, choices=[('SMALL', 'Petit Modèle'), ('MEDIUM', 'Moyen Modèle'), ('BIG', 'Grand Modèle')], max_length=255, null=True, verbose_name='Taille'),
        ),
    ]
