# Generated by Django 3.1 on 2021-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20211114_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedrange',
            options={'ordering': ['range_name', 'capacity', 'the_print']},
        ),
        migrations.RemoveField(
            model_name='coil',
            name='link',
        ),
        migrations.RemoveField(
            model_name='coiltype',
            name='link',
        ),
        migrations.RemoveField(
            model_name='combinedrange',
            name='link',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='link',
        ),
        migrations.RemoveField(
            model_name='finishedproducttype',
            name='link',
        ),
        migrations.RemoveField(
            model_name='labelling',
            name='link',
        ),
        migrations.RemoveField(
            model_name='package',
            name='link',
        ),
        migrations.AddField(
            model_name='coil',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='coiltype',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='combinedrange',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='finishedproducttype',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='labelling',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
        migrations.AddField(
            model_name='package',
            name='the_print',
            field=models.CharField(blank=True, choices=[('MANTOUDJ_BLADI', 'Mantoudj Bladi'), ('BEST_MARKET', 'Best Market'), ('SUPERETTE', 'Superette'), ('SUPER_MARKET', 'Super Market'), ('LIKE', 'Like'), ('Q&P', 'Qualité/Prix'), ('THANKS', 'Thanks'), ('BEST_OF_SHOPPING', 'Best Of Shopping'), ('BIG_SHOP', 'Big Shop'), ('THANK_YOU', 'Thank You'), ('FAMILY_STORE', 'Family Store'), ('TASSAOUK_AL_AFDAL', 'Tassaouk Al Afdal'), ('FRUITS_ET_LEGUMES', 'Fruits Et Légumes'), ('SHOP_EXPRESS', 'Shop Express'), ('SURPRISE', 'Surprise'), ('FRED_PERRY', 'Fred Perry'), ('I_LOVE_SHOPPING', 'I Love Shopping'), ('TOMMY_HILFIGER', 'Tommy Hilfiger'), ('HACKETT', 'Hackett'), ('PHARMACIE', 'Pharmacie'), ('PIZZA', 'Pizza'), ('BOUCHERIE', 'Boucherie'), (None, '--------')], max_length=250, null=True, verbose_name='Impression'),
        ),
    ]
