# Generated by Django 4.0 on 2021-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20211114_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING_EXTRUSION', "En cours d'extrusion"), ('PENDING_DATA', "En attente d'informations"), ('IN_STOCK', 'En Stock'), ('PENDING_PRINTING', "En cours d'impression"), ('PENDING_SHAPING', 'En cours de soudure'), ('CONSUMED', 'Consommée'), ('SOLD', 'Vendue'), ('QUARANTINE', 'En Quarantaine'), ('TO_BE_DESTROYED', 'A Détruire'), ('CUT', 'Coupée')], default='PENDING_EXTRUSION', max_length=25, null=True),
        ),
    ]
