# Generated by Django 4.0 on 2022-01-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_coil_the_print_alter_coiltype_the_print_and_more'),
        ('Product', '0009_finishedproducttype_package_type_and_more'),
    ]

    operations = [
    ]
