# Generated by Django 4.0 on 2022-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_coiltype_longueur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coiltype',
            options={'ordering': ['capacity', 'name']},
        ),
        migrations.RemoveField(
            model_name='coil',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='coiltype',
            name='the_print',
        ),
        migrations.AlterField(
            model_name='coil',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='coiltype',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='finishedproducttype',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='labelling',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='package',
            name='capacity',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('MINI', '15 Mini'), ('SMALL', '19 Petit Modèle'), ('MEDIUM', '25 Moyen Modèle'), ('BIG', '30 Grand Modèle'), ('KOROZO_BIG', '39 Grand Modèle'), ('GGM', '42 Grand Modèle +')], max_length=255, null=True, verbose_name='Taille'),
        ),
    ]
