# Generated by Django 3.1 on 2021-11-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_coil_coiltype_finishedproduct_finishedproducttype_rawmatter'),
        ('StockManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coilsale',
            name='coil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coil_sold', to='Product.coil'),
        ),
        migrations.AddField(
            model_name='loss',
            name='rawmatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.rawmatter'),
        ),
    ]
