# Generated by Django 3.1 on 2021-11-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
        ('Machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('trash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.trash')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Déchet',
                'verbose_name_plural': 'Corrections Déchet',
                'db_table': 'Correction Déchet',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('ref_code', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField()),
                ('quantity_produced', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('process_type', models.CharField(blank=True, choices=[('SHAPING', 'Façonnage'), ('PRINTING', 'Impression'), ('MIXING', 'Mélange'), ('EXTRUSION', 'Extrusion'), ('FINISHED_PRODUCT', 'Production')], max_length=250, null=True)),
                ('state', models.CharField(blank=True, choices=[('PENDING', 'En Cours'), ('FINISHED', 'Terminé')], max_length=250, null=True)),
                ('mix_type', models.CharField(blank=True, choices=[(None, '---------'), ('HAUTE_DENSITE', 'Haute Densité'), ('BASSE_DENSITE', 'Basse Densité'), ('LINEAIRE', 'Linéaire'), ('AUTRE', 'Autre')], max_length=50, null=True)),
                ('mix_perfume', models.CharField(blank=True, choices=[('NOT_PERFUMED', 'Non Parfumé'), ('PERFUMED', 'Parfumé')], max_length=50, null=True)),
                ('consumed', models.CharField(blank=True, choices=[('CONSUMED', 'Consommé'), ('NOT_CONSUMED', 'Non Consommé')], default='NOT_CONSUMED', max_length=50, null=True)),
                ('rectified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Rectifié')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.color', verbose_name='Couleur')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'db_table': 'Production',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PackageConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'unités")),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_consumed', to='Product.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consommation Emballage',
                'verbose_name_plural': 'Consommations Emballage',
                'db_table': 'PackageConsumption',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LabellingConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'étiquettes")),
                ('labelling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labelling_consumed', to='Product.labelling')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labelling_consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consommation Labelling',
                'verbose_name_plural': 'Consommations Labelling',
                'db_table': 'LabellingConsumption',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InkConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantité')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ink_consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consommation Encre',
                'verbose_name_plural': 'Consommations Encre',
                'db_table': 'InkConsumption',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HandleConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de rouleaux')),
                ('handle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handle_consumed', to='Product.handle')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handle_consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consommation Cordon',
                'verbose_name_plural': 'Consommations Cordon',
                'db_table': 'HandleConsumption',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GapRawMatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Stock Atelier Matière Première',
                'verbose_name_plural': 'Corrections Stock Atelier Matière Première',
                'db_table': 'Correction Stock Atelier Matière Première',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GapPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Stock Atelier Emballage',
                'verbose_name_plural': 'Corrections Stock Atelier Emballage',
                'db_table': 'Correction Stock Atelier Emballage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GapLabelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('labelling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.labelling')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Stock Atelier Labelling',
                'verbose_name_plural': 'Corrections Stock Atelier Labelling',
                'db_table': 'Correction Stock Atelier Labelling',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GapHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('handle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.handle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Stock Atelier Cordon',
                'verbose_name_plural': 'Corrections Stock Atelier Cordon',
                'db_table': 'Correction Stock Atelier Cordon',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True, verbose_name='Ecart')),
                ('type_difference', models.CharField(blank=True, choices=[('POSITIVE', 'Ecart Positif'), ('NEGATIVE', 'Ecart Négatif')], max_length=25, null=True, verbose_name="Type de l'écart")),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Production.production')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction',
                'verbose_name_plural': 'Corrections',
                'db_table': 'Correction',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annulation Opération',
                'verbose_name_plural': 'Annulations Opérations',
                'db_table': 'Cancellation',
                'ordering': ['-date'],
            },
        ),
    ]
