# Generated by Django 4.0 on 2022-01-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_auto_20211103_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='ideal_weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
    ]
