# Generated by Django 4.0 on 2022-02-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Production', '0004_production_the_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_production_user', to='auth.user'),
        ),
        migrations.AddField(
            model_name='production',
            name='user3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_production_user', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='production',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_production_user', to='auth.user'),
        ),
    ]
