from django.urls import path, include
from .views import (
    ExtrusionCreateView,
    ShapingCreateView,
    PrintingCreateView,
    ProductMixingListView,
    MixingIndexView,
    MixingListView,
    ExtrusionListView,
    PrintingListView,
    ShapingListView,
    ProductionListView,
    print_ticket,
    print_issue_ticket,
    print_ticket_no_qr,
    print_issue_ticket_no_qr,
    validate_production,
    ExtrusionIndexView,
    PrintingIndexView,
    ShapingIndexView,
    extrusion_coil_list,
    shaping_coil_list,
    printing_coil_list,
    FinishedProductCreateView,
    MachineStopCreateView,
    MachineStopListView,
    delete_production,
    delete_trash,
    delete_machine_stop,
    delete_handle_consumption,
    delete_labelling_consumption,
    defective_coil,
    coil_issues,
    TrashCreateView,
    TrashListView,
    IndexView,
    HandleConsumptionView,
    HandleConsumptionListView,
    LabellingConsumptionView,
    LabellingConsumptionListView,
    InkConsumptionView,
    ConsultingIndexView,
    ConsultingOrdersListView,
    ConsultingMixingListView,
    ConsultingPrintingListView,
    ConsultingExtrusionListView,
    ConsultingShapingListView,
    ConsultingFinishedProductListView,
    ConsultingCoilListView,
    ConsultingTrashListView,
    ConsultingTrashOutListView,
    ConsultingProductCorrectionListView,
    ConsultingTrashCorrectionListView,
    ConsultingWorkshopCorrectionListView,
    ConsultingCancellationListView,
    ConsultingLossListView,
    ConsultingHandleListView,
    ConsultingLabellingListView,
    ConsultingPackageListView,
    ConsultingPartListView,
    ConsultingStockStatusView,
    ConsultingStockWorkshopStatusView,
    ConsultingMachineStopView,
    ConsultingInkConsumptionView,
    RecapPage,
    recap,
    PersonnelIndexView,
    HolidayRequestView,
    validate_holiday_request,
    reject_holiday_request,
    delete_holiday_request,
    print_holiday_request,
    HolidayRequestsListView,
    MyHolidaysListView,
    PointView,
    GlobalPointPage,
    PointPage,
    points,
    general_salaries,
    GeneralSalaryPage,
    global_points,
    my_points,
    CoilUpdateView,
    ProductionUpdateView,
    delete_coil,
    delete_point,
    validate_point,
    SalariesView,
    delete_salary,
    delete_salaries,
    validate_salaries,
    print_salaries,
    employee,
    reset_cws,
    ReportingPage,
    reporting,
    AdminRecapPage,
    admin_recap

)

from StockManager.views import (
    add_to_cart,
    OrderSummaryView,
    validate_order,
    remove_from_cart,

)

app_name = 'production'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('index-mixing/', MixingIndexView.as_view(), name='index-mixing'),
    path('index-consulting/', ConsultingIndexView.as_view(), name='index-consulting'),
    path('order-consulting/', ConsultingOrdersListView.as_view(), name='order-consulting'),
    path('mixing-consulting/', ConsultingMixingListView.as_view(), name='mixing-consulting'),
    path('printing-consulting/', ConsultingPrintingListView.as_view(), name='printing-consulting'),
    path('extrusion-consulting/', ConsultingExtrusionListView.as_view(), name='extrusion-consulting'),
    path('shaping-consulting/', ConsultingShapingListView.as_view(), name='shaping-consulting'),
    path('finished-product-consulting/', ConsultingFinishedProductListView.as_view(), name='finished-product-consulting'),
    path('coil-consulting/', ConsultingCoilListView.as_view(), name='coil-consulting'),
    path('trash-consulting/', ConsultingTrashListView.as_view(), name='trash-consulting'),
    path('trashout-consulting/', ConsultingTrashOutListView.as_view(), name='trashout-consulting'),
    path('product-difference-consulting/', ConsultingProductCorrectionListView.as_view(), name='product-difference-consulting'),
    path('trash-difference-consulting/', ConsultingTrashCorrectionListView.as_view(), name='trash-difference-consulting'),
    path('workshop-difference-consulting/', ConsultingWorkshopCorrectionListView.as_view(), name='workshop-difference-consulting'),
    path('cancellation-consulting/', ConsultingCancellationListView.as_view(), name='cancellation-consulting'),
    path('loss-consulting/', ConsultingLossListView.as_view(), name='loss-consulting'),
    path('handle-consulting/', ConsultingHandleListView.as_view(), name='handle-consulting'),
    path('labelling-consulting/', ConsultingLabellingListView.as_view(), name='labelling-consulting'),
    path('package-consulting/', ConsultingPackageListView.as_view(), name='package-consulting'),
    path('part-consulting/', ConsultingPartListView.as_view(), name='part-consulting'),
    path('ink-consumption-consulting/', ConsultingInkConsumptionView.as_view(), name='ink-consumption-consulting'),
    path('stock-status-consulting/', ConsultingStockStatusView.as_view(), name='stock-status-consulting'),
    path('machine-stop-consulting/', ConsultingMachineStopView.as_view(), name='machine-stop-consulting'),
    path('stock-workshop-status-consulting/', ConsultingStockWorkshopStatusView.as_view(), name='stock-workshop-status-consulting'),
    
    
    
    path('machine-stop/', MachineStopCreateView.as_view(), name='machine-stop'),
    path('machine-stop-list/', MachineStopListView.as_view(), name='machine-stop-list'),
    path('delete-machine-stop/<slug>/',delete_machine_stop,name='delete-machine-stop'),
    
    path('extrusion-create/', ExtrusionCreateView.as_view(), name='extrusion-process'),
    path('extrusion-list/', ExtrusionListView.as_view(), name='extrusion-list'),
    path('recap-page/', RecapPage.as_view(), name='recap-page'),
    path('admin-recap-page/', AdminRecapPage.as_view(), name='admin-recap-page'),
    path(r'^recap/search/', recap, name='recap'),
    path(r'^admin-recap/search/', admin_recap, name='admin-recap'),
    path('shaping-list/', ShapingListView.as_view(), name='shaping-list'),
    path('production-list/', ProductionListView.as_view(), name='production-list'),
    path('print-ticket/<slug>/', print_ticket, name='print-ticket'),
    path('print-issue-ticket/<slug>/', print_issue_ticket, name='print-issue-ticket'),
    path('print-ticket-no-qr/<slug>/', print_ticket_no_qr, name='print-ticket-no-qr'),
    path('print-issue-ticket-no-qr/<slug>/', print_issue_ticket_no_qr, name='print-issue-ticket-no-qr'),

    path('shaping/handle-consumption/', HandleConsumptionView.as_view(), name='handle-consumption'),
    path('shaping/handle-consumption-list/', HandleConsumptionListView.as_view(), name='handle-consumption-list'),
    path('delete-handle-consumption/<slug>/',delete_handle_consumption,name='delete-handle-consumption'),

    path('shaping/labelling-consumption/', LabellingConsumptionView.as_view(), name='labelling-consumption'),
    path('shaping/labelling-consumption-list/', LabellingConsumptionListView.as_view(), name='labelling-consumption-list'),
    path('delete-labelling-consumption/<slug>/',delete_labelling_consumption,name='delete-labelling-consumption'),

    path('printing/ink-consumption/', InkConsumptionView.as_view(), name='ink-consumption'),
    

    path('update-coil/<ref>/', CoilUpdateView.as_view(), name='update-coil'),
    path('delete-coil/<ref>/', delete_coil, name='delete-coil'),


    path('update-production/<slug>/', ProductionUpdateView.as_view(), name='update-production'),

    path('defective-coil/<slug>/', defective_coil, name='defective-coil'),
    path('printing-list/', PrintingListView.as_view(), name='printing-list'),
    path('coil-issues/', coil_issues, name='coil-issues'),
    path('trash-create/', TrashCreateView.as_view(), name='trash-create'),
    path('trash-list/', TrashListView.as_view(), name='trash-list'),
    path('index-extrusion/', ExtrusionIndexView.as_view(), name='index-extrusion'),
    path('index-printing/', PrintingIndexView.as_view(), name='index-printing'),
    path('index-shaping/', ShapingIndexView.as_view(), name='index-shaping'),
    path('extrusion-coil-list/', extrusion_coil_list, name='extrusion-coil-list'),
    path('shaping-coil-list/', shaping_coil_list, name='shaping-coil-list'),
    path('reset-cws/<slug>/', reset_cws, name='reset-cws'),
    path('finishedproduct/', FinishedProductCreateView.as_view(), name='finishedproduct'),
    path('printing-coil-list/', printing_coil_list, name='printing-coil-list'),
    path('shaping/', ShapingCreateView.as_view(), name='shaping-process'),
    path('printing/', PrintingCreateView.as_view(), name='printing-process'),
    path('mixing/', ProductMixingListView.as_view(), name='mixing-process'),
    path('mixing-list/',MixingListView.as_view(),name='mixing-list'),
    path('validate-production/<slug>/',validate_production,name='validate-production'),
    path('delete-production/<slug>/',delete_production,name='delete-production'),
    path('delete-trash/<slug>/',delete_trash,name='delete-trash'),
    
    #
    path('order-validation/', validate_order, name="order-validation"),
    path('order-summary/', OrderSummaryView.as_view(), name="order-summary"),
    path('add-to-order/<slug>/', add_to_cart, name="add-to-order"),
    path('remove-item/<slug>/', remove_from_cart, name="remove-item"),
    
    
    path('request-holiday/', HolidayRequestView.as_view(), name="request-holiday"),
    path('index-personnel/', PersonnelIndexView.as_view(), name="index-personnel"),
    path('accept-holiday-request/<slug>/', validate_holiday_request, name="accept-holiday-request"),
    path('reject-holiday-request/<slug>/', reject_holiday_request, name="reject-holiday-request"),
    path('delete-holiday-request/<slug>/', delete_holiday_request, name="delete-holiday-request"),
    path('print-holiday-request/<slug>/', print_holiday_request, name="print-holiday-request"),
    path('my-holidays/', MyHolidaysListView.as_view(), name="my-holidays"),
    path('holiday-request-list/', HolidayRequestsListView.as_view(), name="holiday-request-list"),

    path('point-create/', PointView.as_view(), name="point-create"),
    path('point-page/', PointPage.as_view(), name='point-page'),
    path('global-point-page/', GlobalPointPage.as_view(), name='global-points-page'),
    path(r'^points/search/', points, name='points'),
    path('global-points/', global_points, name='global-points'),
    path('general-salary-page/', GeneralSalaryPage.as_view(), name='general-salary-page'),
    path('my-points/', my_points, name='my-points'),
    path('general-salaries/', general_salaries, name='general-salaries'),
    path('delete-point/<slug>/', delete_point, name='delete-point'),
    path('validate-point/', validate_point, name='validate-point'),
    path('salaries/', SalariesView.as_view(), name='salaries'),
    path('delete-salary/<slug>/', delete_salary, name='delete-salary'),
    path('delete-salaries/', delete_salaries, name='delete-salaries'),
    path('validate-salaries/', validate_salaries, name='validate-salaries'),
    path('print-salaries/', print_salaries, name='print-salaries'),

    path('employee/<slug>/', employee, name='employee'),

    
    path('reporting-page/', ReportingPage.as_view(), name='reporting-page'),
    path(r'^reporting/search/', reporting, name='reporting'),
    
    
]
