# Generated by Django 3.1 on 2021-11-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modèle')),
                ('slug', models.SlugField(unique=True)),
                ('machine_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro')),
                ('state', models.CharField(blank=True, choices=[('FREE', 'Libre'), ('OCCUPIED', 'Occupé'), ('BROKEN', 'En panne')], default='FREE', max_length=250, null=True, verbose_name='Etat de la machine')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['machine_type', 'machine_number'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type de la machine')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('hours', models.IntegerField(blank=True, default=0, null=True)),
                ('minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('cause', models.CharField(blank=True, choices=[('ELECTRICAL_BREAKDOWN', 'Panne Electrique'), ('MECHANICAL_BREAKDOWN', 'Panne Mécanique'), ('POWER', 'Coupure De Courant'), ('TEFLON', 'Changement Téflon'), ('FILTER', 'Changement Filtre'), ('BLADE', 'Changement Lame'), ('COIL_SHORTAGE', 'Manque De Bobines'), ('CLEAN', 'Nettoyage'), ('OTHER', 'Autre')], max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machine.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
